require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe StructuredNotesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # StructuredNote. As you add validations to StructuredNote, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # StructuredNotesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all structured_notes as @structured_notes" do
      structured_note = StructuredNote.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:structured_notes)).to eq([structured_note])
    end
  end

  describe "GET show" do
    it "assigns the requested structured_note as @structured_note" do
      structured_note = StructuredNote.create! valid_attributes
      get :show, {:id => structured_note.to_param}, valid_session
      expect(assigns(:structured_note)).to eq(structured_note)
    end
  end

  describe "GET new" do
    it "assigns a new structured_note as @structured_note" do
      get :new, {}, valid_session
      expect(assigns(:structured_note)).to be_a_new(StructuredNote)
    end
  end

  describe "GET edit" do
    it "assigns the requested structured_note as @structured_note" do
      structured_note = StructuredNote.create! valid_attributes
      get :edit, {:id => structured_note.to_param}, valid_session
      expect(assigns(:structured_note)).to eq(structured_note)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new StructuredNote" do
        expect {
          post :create, {:structured_note => valid_attributes}, valid_session
        }.to change(StructuredNote, :count).by(1)
      end

      it "assigns a newly created structured_note as @structured_note" do
        post :create, {:structured_note => valid_attributes}, valid_session
        expect(assigns(:structured_note)).to be_a(StructuredNote)
        expect(assigns(:structured_note)).to be_persisted
      end

      it "redirects to the created structured_note" do
        post :create, {:structured_note => valid_attributes}, valid_session
        expect(response).to redirect_to(StructuredNote.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved structured_note as @structured_note" do
        post :create, {:structured_note => invalid_attributes}, valid_session
        expect(assigns(:structured_note)).to be_a_new(StructuredNote)
      end

      it "re-renders the 'new' template" do
        post :create, {:structured_note => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested structured_note" do
        structured_note = StructuredNote.create! valid_attributes
        put :update, {:id => structured_note.to_param, :structured_note => new_attributes}, valid_session
        structured_note.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested structured_note as @structured_note" do
        structured_note = StructuredNote.create! valid_attributes
        put :update, {:id => structured_note.to_param, :structured_note => valid_attributes}, valid_session
        expect(assigns(:structured_note)).to eq(structured_note)
      end

      it "redirects to the structured_note" do
        structured_note = StructuredNote.create! valid_attributes
        put :update, {:id => structured_note.to_param, :structured_note => valid_attributes}, valid_session
        expect(response).to redirect_to(structured_note)
      end
    end

    describe "with invalid params" do
      it "assigns the structured_note as @structured_note" do
        structured_note = StructuredNote.create! valid_attributes
        put :update, {:id => structured_note.to_param, :structured_note => invalid_attributes}, valid_session
        expect(assigns(:structured_note)).to eq(structured_note)
      end

      it "re-renders the 'edit' template" do
        structured_note = StructuredNote.create! valid_attributes
        put :update, {:id => structured_note.to_param, :structured_note => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested structured_note" do
      structured_note = StructuredNote.create! valid_attributes
      expect {
        delete :destroy, {:id => structured_note.to_param}, valid_session
      }.to change(StructuredNote, :count).by(-1)
    end

    it "redirects to the structured_notes list" do
      structured_note = StructuredNote.create! valid_attributes
      delete :destroy, {:id => structured_note.to_param}, valid_session
      expect(response).to redirect_to(structured_notes_url)
    end
  end

end
